apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calc-svc
spec:
  selector:
    app: calc
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1
data:
  name: hodi

---

apiVersion: v1
kind: Secret
metadata:
  name: shhhh
type: Opaque
data:
  password: cGFzc3dvcmQK


