apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calc-svc
spec:
  selector:
    app: calc
  ports:
  - port: 80
    targetPort: 80
