apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calc-svc
spec:
  selector:
    app: calc
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1
data:
  name: hodi

---

apiVersion: v1
kind: Secret
metadata:
  name: shhhh
type: Opaque
data:
  password: cGFzc3dvcmQK
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
